# Generated by Django 5.1.2 on 2024-10-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('accessoryType', models.CharField(choices=[('Helmet', 'Helmet'), ('Lights', 'Lights'), ('Lock', 'Lock'), ('Basket', 'Basket'), ('Pump', 'Pump'), ('Bell', 'Bell'), ('Wheels', 'Wheels'), ('Handlebars', 'Handlebars'), ('Chains', 'Chains'), ('Saddle', 'Saddle'), ('Brakes', 'Brakes')], default='Helmet', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('bikeType', models.CharField(choices=[('BMX', 'BMX'), ('Mountain', 'Mountain'), ('Road', 'Road'), ('Hybrid', 'Hybrid'), ('Cruiser', 'Cruiser'), ('Electric', 'Electric')], default='Mountain', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.transaction')),
                ('saleType', models.CharField(choices=[('Online', 'Online'), ('InStore', 'InStore')], default='InStore', max_length=20)),
                ('trackingID', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionsale',
            name='saleClient',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transactionpurchase',
            name='purchaseClient',
        ),
        migrations.RemoveField(
            model_name='transactionpurchase',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionsale',
            name='transaction',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='client',
            name='isBuyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='isSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Accessory', 'Accessory')], default='Bike', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contactNumber',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='emailAddress',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(default='First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(default='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic Brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='Default Model', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='referenceNumber',
            field=models.CharField(default='REF000', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='releaseYear',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(default='No specifications available'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.CharField(default='images/default.jpg', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='TransactionPurchase',
        ),
        migrations.DeleteModel(
            name='TransactionSale',
        ),
    ]
